services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    image: code-chat-server:latest
    restart: always
    env_file:
      - .env
    environment:
      SERVER_HOST: 0.0.0.0
    ports:
      - "8000:8000"
